import Head from "next/head";
import { Inter } from "next/font/google";
import ProductsList from "../../components/sharedComponents/ProductsList";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>PWA Application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ProductsList limit="8" componentTitle={"Neuesten Produkte"} />
        <div className="ratio ratio-16x9 mb-5">
          <iframe
            width="560"
            height="315"
            src="https://www.youtube.com/embed/3r7d4qhKCp8"
            title="YouTube video player"
          ></iframe>
        </div>
      </main>
    </>
  );
}
