import Head from "next/head";
import { useContext, useEffect, useState } from "react";
import ProductsList from "../../components/sharedComponents/ProductsList";
import CookieContext from "../../context/CookieContext";

export default function Home() {
  const { isCookieApproved } = useContext(CookieContext);
  const [isCookieAllowed, setIsCookieAllowed] = useState(false);

  useEffect(() => {
    setIsCookieAllowed(isCookieAllowed);
  }, [isCookieApproved]);

  return (
    <>
      <Head>
        <title>PWA Application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ProductsList limit="8" componentTitle={"Neuesten Produkte"} />
        {isCookieApproved ? (
          <div className="ratio ratio-16x9 mb-5">
            <iframe
              width="560"
              height="315"
              src="https://www.youtube.com/embed/3r7d4qhKCp8"
              title="YouTube video player"
            ></iframe>
          </div>
        ) : (
          <h4>To view this content you must accept out Cookie Policy</h4>
        )}
      </main>
    </>
  );
}
